version: '3.8'
services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './client'
      args:
        - "--no-cache"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '4200:4200'
    tty: true
      
  server:
    build:
      dockerfile: Dockerfile
      context: './server'
      args:
        - "--no-cache"
    volumes:
      - ./server:/app
    ports:
      - '8080:8080'
    command: ["air", "-c", ".air.toml"]
    tty: true
