# User section

enum Role {
	ADMIN
	USER
}

scalar Time

type Token {
	value: String!
	expiration: Int!
}

type User {
	name: String!
	email: String!
	userID: String!
	role: Role!
	password: String!
	rememberMe: Boolean
	provider: String
	photo: String
	phone: String
	location: String
	gender: String
	createdAt: Time!
	updatedAt: Time!
}

type UserProfile {
	name: String
	email: String
	userID: String
	role: Role
	photo: String
	phone: String
	location: String
	gender: String
}

type UserAuthResponse {
	message: String!
	user: UserProfile
	token: TokenResponse
}

type Message {
	message: String!
}

type TokenResponse {
  accessToken: Token!
  refreshToken: Token!
}

type Query {
	Users: [UserProfile]
	User: UserProfile!
	SocialLogin: UserAuthResponse!
}

type Mutation {
	CreateUser(input: CreateNewUser!): UserAuthResponse!
	LoginUser(input: LoginUser!): UserAuthResponse!
	UpdateUser(input: UpdateUser!): UserAuthResponse!
	DeleteUser: Message!
	DeleteUsers(UserID: String!): Message!
}

input CreateNewUser {
	name: String!
	email: String!
	password: String!
	role: Role
}

input LoginUser {
	email: String!
	password: String!
	rememberMe: Boolean
}

input UpdateUser {
	name: String
	email: String
	photo: String
	phone: String
	location: String
	gender: String
}

# Product section
enum ProductStatus {
	COMPLETED
	PENDING
}

enum PaymentMethod {
	VISA
	PAYPAL
}

type Product {
	productName: String
	productDescription: String
	productCategory: String
	orderId: String
	date: Time
	customerName: String
	productStatus: ProductStatus
	productPrice: Float
	discountPercentage: Float
}