package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"time"

	"github.com/DelaRicch/klock/server/database"
	graphql1 "github.com/DelaRicch/klock/server/graphql/generated"
	"github.com/DelaRicch/klock/server/graphql/models"
	"github.com/DelaRicch/klock/server/helpers"
)

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input models.CreateNewUser) (*models.UserAuthResponse, error) {
	_, err := GinContextFromContext(ctx)

	if err != nil {
		return nil, fmt.Errorf("failed to retrieve gin.Context: %w", err)
	}

	provider := "Klock"

	// Check if the input.Email is typeof email
	if !helpers.IsValidEmail(input.Email) {
		return &models.UserAuthResponse{Success: false, Message: "Invalid email"}, nil
	}

	user := &models.User{
		Name:      input.Name,
		Email:     input.Email,
		Password:  input.Password,
		Role:      models.RoleUser,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	if input.Role != nil {
		user.Role = *input.Role
	}

	// Check if user already exist
	var existingUser = models.User{}
	result := database.DB.Where("email = ?", user.Email).First(&existingUser)
	if result.RowsAffected > 0 {
		return &models.UserAuthResponse{Success: false, Message: "User already exist"}, nil
	}

	// Hash password
	hashedPassword, err := helpers.HashPassword(user.Password)
	if err != nil {
		return &models.UserAuthResponse{Success: false, Message: "Error hashing password"}, err
	}
	user.Password = hashedPassword

	// Generate User ID and other fields
	user.UserID = helpers.GenerateID("KLOCK-USER")
	user.Provider = &provider

	fmt.Println(user.UserID)

	result = database.DB.Create(user)
	if result.Error != nil {
		return &models.UserAuthResponse{Success: false, Message: result.Error.Error()}, result.Error
	}

	// Generate JWT
	refreshTkn, token, exp, rfExp, err := helpers.CreateJwtToken(user)
	if err != nil {
		return &models.UserAuthResponse{Success: false, Message: errorRfTokenMsg}, err
	}

	accessToken := models.Token{
		Value:      token,
		Expiration: exp,
	}

	refreshToken := models.Token{
		Value:      refreshTkn,
		Expiration: rfExp,
	}

	return &models.UserAuthResponse{
		Success: true,
		Message: fmt.Sprintf("%s registered successfully", user.Name),
		User: &models.UserProfile{
			UserID:   &user.UserID,
			Name:     &user.Name,
			Email:    &user.Email,
			Role:     &user.Role,
			Photo:    user.Photo,
			Phone:    user.Phone,
			Location: user.Location,
			Gender:   user.Gender,
		},
		Token: &models.TokenResponse{
			AccessToken:  &accessToken,
			RefreshToken: &refreshToken,
		},
	}, nil
}

// UpdateUser is the resolver for the UpdateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, userID string, input models.UpdateUser) (*models.UserAuthResponse, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - UpdateUser"))
}

// DeleteUser is the resolver for the DeleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (*models.UserAuthResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - DeleteUser"))
}

// Users is the resolver for the Users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.UserProfile, error) {
	panic(fmt.Errorf("not implemented: Users - Users"))
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, userID string) (*models.UserProfile, error) {
	panic(fmt.Errorf("not implemented: User - User"))
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
const errorRfTokenMsg string = "Error generating refresh token"
