// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateNewUser struct {
	Name     string `json:"name" gorm:"name"`
	Email    string `json:"email" gorm:"email"`
	Password string `json:"password" gorm:"password"`
	Role     *Role  `json:"role,omitempty" gorm:"role"`
}

type LoginUser struct {
	Email      string `json:"email" gorm:"email"`
	Password   string `json:"password" gorm:"password"`
	RememberMe *bool  `json:"rememberMe,omitempty" gorm:"rememberMe"`
}

type Message struct {
	Message string `json:"message" gorm:"message"`
}

type Mutation struct {
}

type Product struct {
	ProductName        *string        `json:"productName,omitempty" gorm:"productName"`
	ProductDescription *string        `json:"productDescription,omitempty" gorm:"productDescription"`
	ProductCategory    *string        `json:"productCategory,omitempty" gorm:"productCategory"`
	OrderID            *string        `json:"orderId,omitempty" gorm:"orderId"`
	Date               *time.Time     `json:"date,omitempty" gorm:"date"`
	CustomerName       *string        `json:"customerName,omitempty" gorm:"customerName"`
	ProductStatus      *ProductStatus `json:"productStatus,omitempty" gorm:"productStatus"`
	ProductPrice       *float64       `json:"productPrice,omitempty" gorm:"productPrice"`
	DiscountPercentage *float64       `json:"discountPercentage,omitempty" gorm:"discountPercentage"`
}

type Query struct {
}

type Token struct {
	Value      string `json:"value" gorm:"value"`
	Expiration int64  `json:"expiration" gorm:"expiration"`
}

type TokenResponse struct {
	AccessToken  *Token `json:"accessToken" gorm:"accessToken"`
	RefreshToken *Token `json:"refreshToken" gorm:"refreshToken"`
}

type UpdateUser struct {
	Name     *string `json:"name,omitempty" gorm:"name"`
	Email    *string `json:"email,omitempty" gorm:"email"`
	Photo    *string `json:"photo,omitempty" gorm:"photo"`
	Phone    *string `json:"phone,omitempty" gorm:"phone"`
	Location *string `json:"location,omitempty" gorm:"location"`
	Gender   *string `json:"gender,omitempty" gorm:"gender"`
}

type User struct {
	Name       string    `json:"name" gorm:"name"`
	Email      string    `json:"email" gorm:"email"`
	UserID     string    `json:"userID" gorm:"userID"`
	Role       Role      `json:"role" gorm:"role"`
	Password   string    `json:"password" gorm:"password"`
	RememberMe *bool     `json:"rememberMe,omitempty" gorm:"rememberMe"`
	Provider   *string   `json:"provider,omitempty" gorm:"provider"`
	Photo      *string   `json:"photo,omitempty" gorm:"photo"`
	Phone      *string   `json:"phone,omitempty" gorm:"phone"`
	Location   *string   `json:"location,omitempty" gorm:"location"`
	Gender     *string   `json:"gender,omitempty" gorm:"gender"`
	CreatedAt  time.Time `json:"createdAt" gorm:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt" gorm:"updatedAt"`
}

type UserAuthResponse struct {
	Message string         `json:"message" gorm:"message"`
	User    *UserProfile   `json:"user,omitempty" gorm:"user"`
	Token   *TokenResponse `json:"token,omitempty" gorm:"token"`
}

type UserProfile struct {
	Name     *string `json:"name,omitempty" gorm:"name"`
	Email    *string `json:"email,omitempty" gorm:"email"`
	UserID   *string `json:"userID,omitempty" gorm:"userID"`
	Role     *Role   `json:"role,omitempty" gorm:"role"`
	Photo    *string `json:"photo,omitempty" gorm:"photo"`
	Phone    *string `json:"phone,omitempty" gorm:"phone"`
	Location *string `json:"location,omitempty" gorm:"location"`
	Gender   *string `json:"gender,omitempty" gorm:"gender"`
}

type PaymentMethod string

const (
	PaymentMethodVisa   PaymentMethod = "VISA"
	PaymentMethodPaypal PaymentMethod = "PAYPAL"
)

var AllPaymentMethod = []PaymentMethod{
	PaymentMethodVisa,
	PaymentMethodPaypal,
}

func (e PaymentMethod) IsValid() bool {
	switch e {
	case PaymentMethodVisa, PaymentMethodPaypal:
		return true
	}
	return false
}

func (e PaymentMethod) String() string {
	return string(e)
}

func (e *PaymentMethod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentMethod", str)
	}
	return nil
}

func (e PaymentMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ProductStatus string

const (
	ProductStatusCompleted ProductStatus = "COMPLETED"
	ProductStatusPending   ProductStatus = "PENDING"
)

var AllProductStatus = []ProductStatus{
	ProductStatusCompleted,
	ProductStatusPending,
}

func (e ProductStatus) IsValid() bool {
	switch e {
	case ProductStatusCompleted, ProductStatusPending:
		return true
	}
	return false
}

func (e ProductStatus) String() string {
	return string(e)
}

func (e *ProductStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductStatus", str)
	}
	return nil
}

func (e ProductStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
